language: python
services:
- postgresql
env:
- DATABASE_URL='postgres://postgres:@localhost:5432/kevgathuku_test' DJANGO_SETTINGS_MODULE='kevgathuku.settings.testing'
  SECRET_KEY='3zK7985pe$2KG!bYQ]puX1P4[401okcrxfbxdfxca9b'
python:
- '2.7'
addons:
  postgresql: '9.3'
install:
- pip install -r requirements/testing.txt
before_script:
- psql -c 'create database sermonbuddy_test;' -U postgres
- python manage.py migrate --noinput
- python manage.py collectstatic --noinput
script:
- python manage.py test
deploy:
  provider: heroku
  api_key:
    secure: IxsmvJMpNZOAlmI1uJA2IdiQN0vcQmEO8cB/lKt/GFqY+pQsHHb6hi9w0cjvDiXDNuWRsg/cDz+mY44FrAju5NzyM0+PFIe9dC3c4Rs0cVlcY9P3/mBh6qh9ZnG+C5+hGrxB3xLlBi9J+R7daDnqXZuGpG/gRq2vjU2i4XzGDL0=
  skip_cleanup: true
  app: kevgathuku
  on:
    repo: kevgathuku/kevgathuku
